package com.correios.gui;

import com.correios.utilities.HibernateUtil;
import java.awt.Graphics;
import java.awt.Image;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import org.hibernate.SessionFactory;

/**
 * Tela principal da aplicacao, esta deve ser a raiz das demais telas internas
 * (JInternalFrames) pois poussi o JDesktopPane e a barra de menus.
 *
 * @version 1.0
 * @author fabiosperotto
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private final ResourceBundle traducoes;

    /**
     * Constructor da tela principal
     *
     * @param traducoes ResourceBundle arquivo de traducoes carregado na main
     * para usar na aplicacao
     */
    public TelaPrincipal(ResourceBundle traducoes) {
        initComponents();
        this.traducoes = traducoes;
        this.verificarConexaoBD();
        this.traduzirGUI();

    }

    /**
     * Realiza a checagem de conectividade com banco de dados. Caso nao exista a
     * conexao, vai avisar ao usuario encerrando a aplicacao posteriormente
     */
    private void verificarConexaoBD() {
        SessionFactory sessionFactory = HibernateUtil.getSessionFactory();
        if (sessionFactory == null) {
            JOptionPane.showMessageDialog(this,
                    this.traducoes.getString("erro_conexao_desc"),
                    this.traducoes.getString("erro_conexao_titulo"),
                    JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }

    /**
     * Realiza a traducao de textos desta tela (jlabels e demais informacoes
     * visuais)
     */
    private void traduzirGUI() {
        jMenuCadastros.setText(this.traducoes.getString("menu_cadastros"));
        jMenuItemPessoas.setText(this.traducoes.getString("menu_item_pessoas"));
        jMenuSobre.setText(this.traducoes.getString("menu_ajuda"));
        jmenuitemSobre.setText(this.traducoes.getString("menu_item_sobre"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icone = new ImageIcon(getClass().getResource("/img/back.jpg"));
        Image imagem = icone.getImage();
        jDesktop = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(imagem,0,0,getWidth(),getHeight(), this);
            }
        };
        jMenuBar = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemPessoas = new javax.swing.JMenuItem();
        jMenuSobre = new javax.swing.JMenu();
        jmenuitemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(" Correios ERP");
        setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout jDesktopLayout = new javax.swing.GroupLayout(jDesktop);
        jDesktop.setLayout(jDesktopLayout);
        jDesktopLayout.setHorizontalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );
        jDesktopLayout.setVerticalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );

        jMenuCadastros.setMnemonic('C');
        jMenuCadastros.setText("Cadastros");

        jMenuItemPessoas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jMenuItemPessoas.setMnemonic('P');
        jMenuItemPessoas.setText("Pessoas");
        jMenuItemPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPessoasActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemPessoas);

        jMenuBar.add(jMenuCadastros);

        jMenuSobre.setMnemonic('A');
        jMenuSobre.setText("Ajuda");
        jMenuSobre.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jMenuSobreMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSobreActionPerformed(evt);
            }
        });

        jmenuitemSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jmenuitemSobre.setMnemonic('S');
        jmenuitemSobre.setText("Sobre");
        jmenuitemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenuitemSobreActionPerformed(evt);
            }
        });
        jMenuSobre.add(jmenuitemSobre);

        jMenuBar.add(jMenuSobre);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Abrir tela de cadastro de Pessoas, deve remover outras telas internas
     * abertas no JDestopPane.Possui Thread para exibir tela de loading (gif animado)
     *
     * @param evt evento de clique principal do mouse
     */
    private void jMenuItemPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPessoasActionPerformed
        this.jDesktop.removeAll();
        SwingUtilities.invokeLater(() -> { //invocacao segura do jframe
            TelaLoading loading = new TelaLoading(this.traducoes);
            loading.setLocationRelativeTo(null);
            loading.setVisible(true);
            new Thread(() -> {
                InternalPessoas internaPessoas = new InternalPessoas(this.traducoes);
                this.jDesktop.add(internaPessoas);
                internaPessoas.carregarDados();//realizar o carregamento pesado enquanto loading ativo
                
                SwingUtilities.invokeLater(() -> {
                    //quando o jframe final carregar a tela de loading deve desaparecer:
                    internaPessoas.setVisible(true);
                    loading.setVisible(false);
                });
            }).start();
        });

    }//GEN-LAST:event_jMenuItemPessoasActionPerformed

    private void jMenuSobreMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMenuSobreMenuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuSobreMenuKeyPressed

    private void jMenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuSobreActionPerformed

    /**
     * Abre a tela Sobre para explicacoes do projeto
     *
     * @param evt evento de clique principal do mouse
     */
    private void jmenuitemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenuitemSobreActionPerformed
        InternalSobre telaSobre = new InternalSobre();
        this.jDesktop.add(telaSobre);
        telaSobre.setVisible(true);
    }//GEN-LAST:event_jmenuitemSobreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenuItem jMenuItemPessoas;
    private javax.swing.JMenu jMenuSobre;
    private javax.swing.JMenuItem jmenuitemSobre;
    // End of variables declaration//GEN-END:variables
}
